account_id = "e3c8765289b1bb60cdb2680f0834d7bb"
name = "liang-kubur-sim"
pages_build_output_dir = "public"
compatibility_date = "2025-04-01"

[vars]
# Non-secret defaults (override in dashboard if needed)
DEEPGRAM_TTS_MODEL = "aura-2-thalia-en"